services:
    canabelle.cms.user.security.interactive_login_listener:
        class: Canabelle\CMSUserBundle\Security\LoginListener
        arguments: [@request_stack, @fos_user.user_manager, @doctrine.orm.default_entity_manager, @session, @canabelle.web.exception_handler]
        tags:
        - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    ok99.privatezone.user.form.type.user_avatar:
        class: Canabelle\CMSUserBundle\Form\UserAvatarType
        tags:
            - { name: form.type, alias: user_avatar }
